package modelos;
// Generated 3/04/2016 02:58:28 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String nusario;
     private Usuario usuario;
     private String password;

    public Login() {
    }

    public Login(Usuario usuario, String password) {
       this.usuario = usuario;
       this.password = password;
    }
   
    public String getNusario() {
        return this.nusario;
    }
    
    public void setNusario(String nusario) {
        this.nusario = nusario;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


