package modelos;
// Generated 3/04/2016 02:58:28 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nusario;
     private String nombre;
     private String apellidos;
     private Integer edad;
     private Login login;

    public Usuario() {
    }

	
    public Usuario(String nusario) {
        this.nusario = nusario;
    }
    public Usuario(String nusario, String nombre, String apellidos, Integer edad, Login login) {
       this.nusario = nusario;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.edad = edad;
       this.login = login;
    }
   
    public String getNusario() {
        return this.nusario;
    }
    
    public void setNusario(String nusario) {
        this.nusario = nusario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }




}


